# AI CLI Configuration
ai:
  apiKey: "your-api-key-here"  # Required: Your API key
  model: "default-model"      # Default AI model
  basePath: ""                # Optional: Custom API endpoint
  stream: false               # Enable streaming response
